PACKAGE_NAME="virtualbox-guest-modules-dkms"
PACKAGE_VERSION="7.2.8"
BUILD_EXCLUSIVE_KERNEL="^([56]\.[0-9]+\.|7\.[0-0]\.)" # only build for kernels v5.x.x up to and including v7.0.x
BUILT_MODULE_NAME[0]="vboxguest"
BUILT_MODULE_LOCATION[0]="vboxguest"
DEST_MODULE_LOCATION[0]="/extra/dkms"
BUILT_MODULE_NAME[1]="vboxsf"
BUILT_MODULE_LOCATION[1]="vboxsf"
DEST_MODULE_LOCATION[1]="/extra/dkms"
AUTOINSTALL="yes"
