#######################################################
# Support for multiple mirrors is somewhat incomplete #
#######################################################
#       Please avoid using the Main Repository        #
#    http://mirrors.redcorelinux.org/redcorelinux     #
#  as the bandwidth is limited, use mirrors instead   #
#######################################################
#    Uncomment only one mirror from the list bellow   #
#######################################################

# [redcore-main-stable]
# sync-uri = http://mirrors.redcorelinux.org/redcorelinux/arm64/packages/
# location = /var/cache/packages

# [redcore-main-testing]
# sync-uri = http://mirrors.redcorelinux.org/redcorelinux/arm64/packages-next/
# location = /var/cache/packages

# [redcore-princeton-stable]
# sync-uri = http://mirror.math.princeton.edu/pub/redcorelinux/arm64/packages/
# location = /var/cache/packages

# [redcore-princeton-testing]
# sync-uri = http://mirror.math.princeton.edu/pub/redcorelinux/arm64/packages-next/
# location = /var/cache/packages

# [redcore-alpix-stable]
# sync-uri = http://mirror.alpix.eu/redcorelinux/arm64/packages/
# location = /var/cache/packages

# [redcore-alpix-testing]
# sync-uri = http://mirror.alpix.eu/redcorelinux/arm64/packages-next/
# location = /var/cache/packages

# [redcore-yandex-stable]
# sync-uri = http://mirror.yandex.ru/mirrors/redcorelinux/arm64/packages/
# location = /var/cache/packages

# [redcore-yandex-testing]
# sync-uri = http://mirror.yandex.ru/mirrors/redcorelinux/arm64/packages-next/
# location = /var/cache/packages
